/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package checkerboard;

import javafx.scene.shape.Rectangle;
import javafx.scene.layout.AnchorPane;
import javafx.scene.paint.Color;
/**
 *
 * @author Yi Zhu
 */
public class Checkerboard {
    
    private int numRows;
    private int numCols;
    private double boardWidth;
    private double boardHeight;   
    private double rectangleWidth;
    private double rectangleHeight;  
    private Color lightColor = Color.RED;
    private Color darkColor = Color.BLACK;
        
    private AnchorPane anchorPane;
    //first constructor
    public Checkerboard(int numRows, int numCols, double boardWidth, double boardHeight) {
        this.numRows = numRows;
        this.numCols = numCols; 
        this.boardWidth = boardWidth;
        this.boardHeight = boardHeight;
        rectangleWidth = boardWidth / numCols;
        rectangleHeight = boardHeight / numRows;
    }
    //second constructor
    public Checkerboard(int numRows, int numCols, double boardWidth, double boardHeight, Color lightColor, Color darkColor) {
       this(numRows, numCols, boardWidth, boardHeight);
       this.lightColor = lightColor;
       this.darkColor = darkColor;
    }
    
    // builds the board UI and returns an AnchorPane as the root object
    public AnchorPane build() {
        anchorPane = new AnchorPane();
        anchorPane.setPrefSize(boardWidth, boardHeight);
        for (int row = 0; row < numRows; row++) {
            for (int col = 0; col < numCols; col++) {
                Rectangle rectangle = new Rectangle(col * rectangleWidth, row * rectangleHeight, rectangleWidth, rectangleHeight);
                Color color = darkColor;
                if ((col %2) == (row % 2)) {
                    color = lightColor;
                }
                rectangle.setFill(color);
                anchorPane.getChildren().add(rectangle);
            }
        }
        return anchorPane;
    }
    
    // returns the AnchorPane generated by build() or null if one hasn’t been built yet
    public AnchorPane getBoard() 
    {
        return anchorPane;
    }
    
    //additional public getters
    public int getNumRows() 
    {
        return numRows;
    }
    
    public int getNumCols()
    {
        return numCols;
    }
    
    public double getWidth()  
    {
        return boardWidth;
    }
    
    public double getHeight() 
    {
        return boardHeight;
    }
    
    public Color getLightColor() 
    {
        return lightColor;
    }
    
    public Color getDarkColor() 
    {
        return darkColor;
    }
    
    public double getRectangleWidth() 
    {
        return rectangleWidth;
    }
    
    public double getRectangleHeight() 
    {
        return rectangleHeight;
    }
    
}
